  export const products = [
    {
      id: 1,
      name: "Premium Wireless Headphones",
      brand: "TechSound",
      price: 199.99,
      originalPrice: 249.99,
      rating: 4.5,
      reviewCount: 1256,
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop",
      badge: "Best Seller",
      inStock: false,
      fastDelivery: true,
      freeShipping: true,
      colors: ["Black", "White", "Blue"],
      category: "Electronics"
    },
    {
      id: 2,
      name: "4K Ultra HD Smart TV 55\"",
      brand: "VisionTech",
      price: 499.99,
      originalPrice: 699.99,
      rating: 4.7,
      reviewCount: 892,
      image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=300&fit=crop",
      badge: "Top Rated",
      inStock: true,
      fastDelivery: true,
      freeShipping: true,
      colors: ["Black"],
      category: "Electronics"
    },
    {
      id: 3,
      name: "Gaming Mechanical Keyboard",
      brand: "GameTech",
      price: 129.99,
      originalPrice: 179.99,
      rating: 4.6,
      reviewCount: 743,
      image: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400&h=300&fit=crop",
      badge: "Gamer's Choice",
      inStock: true,
      fastDelivery: true,
      freeShipping: true,
      colors: ["Black", "White", "Red"],
      category: "Electronics"
    },
    {
      id: 4,
      name: "Professional DSLR Camera",
      brand: "PhotoPro",
      price: 899.99,
      originalPrice: 1199.99,
      rating: 4.8,
      reviewCount: 687,
      image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=300&fit=crop",
      badge: "Pro Choice",
      inStock: true,
      fastDelivery: false,
      freeShipping: true,
      colors: ["Black"],
      category: "Electronics"
    },
    {
      id: 5,
      name: "Luxury Leather Sofa",
      brand: "ComfortHome",
      price: 1299.99,
      originalPrice: 1799.99,
      rating: 4.4,
      reviewCount: 534,
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop",
      badge: "Premium",
      inStock: true,
      fastDelivery: false,
      freeShipping: true,
      colors: ["Brown", "Black"],
      category: "Furniture"
    },
    {
      id: 6,
      name: "Wireless Noise-Canceling Earbuds",
      brand: "SoundMax",
      price: 149.99,
      originalPrice: 199.99,
      rating: 4.3,
      reviewCount: 421,
      image: "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=400&h=300&fit=crop",
      badge: "Popular",
      inStock: true,
      fastDelivery: true,
      freeShipping: true,
      colors: ["Black", "White", "Blue"],
      category: "Electronics"
    },
    {
      id: 7,
      name: "Smart Fitness Watch",
      brand: "FitTech",
      price: 249.99,
      originalPrice: 329.99,
      rating: 4.5,
      reviewCount: 356,
      image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&h=300&fit=crop",
      badge: "Health Focus",
      inStock: true,
      fastDelivery: true,
      freeShipping: true,
      colors: ["Black", "Pink", "Blue"],
      category: "Electronics"
    },
    {
      id: 8,
      name: "Coffee Maker Pro",
      brand: "BrewMaster",
      price: 189.99,
      rating: 4.2,
      reviewCount: 298,
      image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=300&fit=crop",
      inStock: true,
      fastDelivery: false,
      freeShipping: true,
      colors: ["Black", "White"],
      category: "Appliances"
    }
  ]
